#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d • • • • • • • • •

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a kcalc state=floating
#bspc rule -a kitty state=pseudo_tiled
bspc rule -a adwaita-steam-gtk state=floating
bspc rule -a zenity state=pseudo_tiled
bspc rule -a msnmsgr.exe state=floating 

bspc config focused_border_color "#b4befe"
bspc config normal_border_color "#313244"

feh --bg-fill ~/Pictures/wallpaper.png &
picom -b --config ~/.config/picom/picom.conf &
setxkbmap us,ru -option 'grp:alt_shift_toggle' &
polybar -c ~/.config/polybar/config.ini &
export QT_QPA_PLATFORMTHEME=qt6ct &
xset s off -r -dpms &
sh /home/user/.config/bspwm/autostart &
